const UsersActionTypes = {
  FETCH_USERS_START: "FETCH_USERS_START",
  FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
  FETCH_USERS_FAILURE: "FETCH_USERS_FAILURE",
  EDIT_USERS: "FETCH_USERS",
  ADD_USER_ACTIVITY: "ADD_USER_ACTIVITY",
  EDIT_USER_ACTIVITY: "EDIT_USER_ACTIVITY",
};

export default UsersActionTypes;
