const WorkoutActionTypes = {
  FETCH_WORKOUTS_START: "FETCH_WORKOUTS_START",
  FETCH_WORKOUTS_SUCCESS: "FETCH_WORKOUTS_SUCCESS",
  FETCH_WORKOUTS_FAILURE: "FETCH_WORKOUTS_FAILURE",
  ADD_WORKOUT: "ADD_WORKOUT",
  EDIT_WORKOUT: "EDIT_WORKOUT",
  REMOVE_WORKOUT: "REMOVE_WORKOUT",
};

export default WorkoutActionTypes;
