const WorkoutActionTypes = {
  FETCH_WORKOUTS_START: "FETCH_WORKOUTS_START",
  FETCH_WORKOUTS_SUCCESS: "FETCH_WORKOUTS_SUCCESS",
  FETCH_WORKOUTS_FAILURE: "FETCH_WORKOUTS_FAILURE",
};

export default WorkoutActionTypes;
